### ISSUE TITLE
conda env setup

### ISSUE THREAD

**Issue by antoine4ucsd** [cov-lineages/pangolin#117]
Hello 
I am trying to install pangolin on my Mac (catalina 10.15.7) 
I have anaconda installed and running but I got the attached error when trying to compile the environnment...
any suggestion???

thank you for your amazing work on COVID-19. 

[pangolin.log.txt](https://github.com/cov-lineages/pangolin/files/5759212/pangolin.log.txt)

**Comment by aineniamh** [comment]
Hi @antoine4ucsd, sorry to hear of the error. I've had a read of the log and it seems that pysam has failed to build on your machine. I think the issue is your machine doesn't have a version of gcc installed 
`error: command 'gcc' failed with exit status 1`, 

I've had a quick search and it's come up before for macs when pip installing other tools. Many systems come with gcc natively, and if you have developer tools installed on your Mac it might have gcc with that. However to solve it for running pangolin, if you try running the following, I think this will resolve the issue!
```
conda activate pangolin
conda install -c conda-forge gcc
```
Then try building the pangolin environment again!

**Comment by antoine4ucsd** [comment]
trying now. I will get back to you asap
thank you so much for the quick reply and your amazing work. 
I wish you the best for this new year

**Comment by antoine4ucsd** [comment]
no more luck
I had to run 
``
conda install -c conda-forge/label/broken gcc
``
to install gcc on the new env because gcc on conda-forge is not available anymore.
gcc install worked but pangolin install raises the same error. see log attached...

thank you again

[pangolin_log.txt](https://github.com/cov-lineages/pangolin/files/5760630/pangolin_log.txt)

**Comment by aineniamh** [comment]
Hmm, that's a shame. I'm not sure what the issue is- I'd suggest updating your miniconda to miniconda 3, instead of 2 (https://docs.conda.io/en/latest/miniconda.html) in case it's something about the installer itself that's not working.

**Comment by antoine4ucsd** [comment]
ok, thanks for the advice. I will keep you informed

**Comment by antoine4ucsd** [comment]
Here's my fix:
create a python3 env
Manually install clang_osx-64 with
``
conda install -c conda-forge clang_osx-64
``

then and only then, install pangolin env. Now it works!
thank you for this very precious tool.

**Comment by aineniamh** [comment]
Ah thanks @antoine4ucsd for the fix! Glad you've got it working!
