### ISSUE TITLE
Essential variant-set out of defining variants for calling a certain lineage (e.g. B.1.1.7)?

### ISSUE THREAD

**Issue by alexadn** [cov-lineages/pangolin#154]
Dear pangolin team,
On https://cov-lineages.org/global_report_... it is given that pangolin calls a certain international VOC lineage if e.g. in case of B.1.1.7 5 of the 17 defining variants are found. Does that mean the lineage is called if any 5 of the e.g. 17 are called or are specific variants essential for calling the lineage? If so where in the docs or code can I find out which variants are essential?
Thank you!
Best,
Alex

**Comment by aineniamh** [comment]
Dear Alex,

We call lineage B.1.1.7 with any 5 of the mutations shown here:
https://github.com/cov-lineages/pangolin/blob/master/pangolin/data/config_b.1.1.7.csv. You'll also notice in the report you linked, the first table has the same set of mutations (https://cov-lineages.org/global_report_B.1.1.7.html).

The mutations are weighted equally because they all occurred along the long basal branch of B.1.1.7, but we have the lower threshold to allow for some missing data.

Hope this helps clarify,

Áine

Áine Niamh O'Toole

Rambaut Lab
Institute for Evolutionary Biology
University of Edinburgh

contact: aine.otoole@ed.ac.uk | aineotoole.co.uk | @AineToole

________________________________
