### ISSUE TITLE
Uk variant not in PangolinLearn

### ISSUE THREAD

**Issue by hudenise2** [cov-lineages/pangolin#176]
Hi,
I'm running Lineagespot which start by downloading the decision_tree_rules.txt (from https://raw.githubusercontent.com/cov-lineages/pangoLEARN/master/pangoLEARN/data/decision_tree_rules.txt).
However I could not repeated the results obtained by the author of Lineagespot paper. A bit more digging indicated that B.1.1.7 (the UK variant) was not present in my output and in fact completely absent from the downloaded decision_tree_rules.txt.
This is strange as others VOC/VUI are present.
I would really appreciate if you could add it if this is a mistake or explain to me why there are no rules for this VOC as it is still circulating
Thanks

**Comment by aineniamh** [comment]
Hi @hudenise2, the latest model has B.1.1.7 in, previously we've just used post-doc variant testing to assign B.1.1.7. This wasn't in error, rather intentionally to be able to define explicit thresholds for assigning B.1.1.7. 

We're also planning in the near future to move to a hierarchical logistic regression-type model, rather than a decision tree, and the decision tree file may not be maintained in the future subject to resource availability.
