### ISSUE TITLE
Ambiguity in usher mode assignments impacting large proportions of certain VOCs/VUIs 

### ISSUE THREAD

**Issue by fmaguire** [cov-lineages/pangolin#217]
## Issue
Pangolin with `--usher` compared to default `pangoLEARN` model seems prone to assigning to general parental lineages.

Running the 45,290 Canadian genomes in GISAID using `pangolin canada_seqs.fasta --outdir pangolearn`and `pangolin --usher canada_seqs.fasta --outdir pangousher` and comparing resulted in ~10.7% of genomes with divergent assignments.

These were largely (64.4%) pangoLEARN having an assignment to a specific lineage e.g., B.1.351 or B.1.525 while usher assigned the same genomes to the B.1 parental lineages.  Here are all the most frequent re-assignments (>25 occurrences) between pangolearn -> usher for the Canadian GISAID genomes as of the `metadata_2021-05-28` nextstrain digest.

```
B.1.525 -> B.1            911
B.1.1 -> B.1.1.409        725
B.1.2 -> B.1              619
B.1.1.318 -> B.1          577
B.1.351 -> B.1            407
B.1.2 -> B.1.596          278
B.1.91 -> B.1             235
B.1.1.121 -> B.1.1.409    148
B.1.346 -> B.1             83
B.1.243 -> B.1             58
B.1.36.8 -> B.1.36         57
B.1 -> B.1.1.318           47
B.1.1 -> B.1               43
B.1.160 -> B.1             35
B.1.349 -> B.1             27
```

The main concern is that this seemed to involve VOCs/VUIs or lineages being monitored (per PHE classifications), including 98% of B.1.525s in Canada and 67% of B.1.351 genomes:

```
Reassigned           % 	         n
B.1.620 	100.000000 	2
B.1.525 	98.699892 	911
B.1.1.318 	92.172524 	577
B.1.351 	67.326733 	408
B.1.1.1 	34.090909 	15
B.1.1.28 	33.333333 	2
B.1.617.1 	32.432432 	12
B.1.429 	2.500000 	1
P.1 	        0.356125 	10
B.1.1.7 	0.029994 	2 
```

Interestingly, every B.1.351 assigned as B.1 when using `--usher` had a `cB.1.351` scorpio call.  Similarly, all the B.1.525s assigned as B.1 had a `cB.1.525` scorpio call.  From what I understand of how usher works it should only be assigning to a parental lineage if there are multiple lineages within B.1 with equally parsimonious sets of mutations for the the query sequences.  Although that seems odd as presumably the same underlying data is being used to train the pangolearn model as well?

Could there be an issue with the genomes representing certain B.1 sublineages in the usher protobuf reference tree?

## Environment
- pangolin repo conda env
- pangolin v3.0.3
- pangolearn 2021-05-27
- scorpio v0.3
- constellations v0.0.2

## Reproduction
I've attached a fasta file ([canada_b1351_b1525_examples.fasta.txt](https://github.com/cov-lineages/pangolin/files/6571450/canada_b1351_b1525_examples.fasta.txt)) with 10 randomly selected Canadian B.1.351s and B.1.525s from GISAID assigned as B.1 by `--usher` mode.

```
mv canada_b1351_b1525_examples.fasta.txt canada_b1351_b1525_examples.fasta
pangolin canada_b1351_b1525_examples.fasta --outdir pangolearn
pangolin canada_b1351_b1525_examples.fasta --usher --outdir pusher
```

**Comment by AngieHinrichs** [comment]
Thank you Finlay!  I will take a look.

**Comment by AngieHinrichs** [comment]
Currently, usher can annotate only one node (branch) of a tree as the root of a lineage, and for a few lineages such as B.1.351 and B.1.525, the current lineageTree.pb tree has more than one branch with the mutations common to sequences in the lineage.  If one of those branches has at least 60% of the lineage's representative sequences (from lineages.metadata.csv in the cov-lineages/pango-designation repository), then the lineage is assigned to that branch -- call that the "major" branch for the lineage (which ideally should be monophyletic on the tree, but trees are usually not perfect).  If usher places an input sequence on a "minor" branch, then unfortunately it will not assign that lineage.

For example, these are the mutations associated with each node on the path from root to the node assigned to B.1.351 in lineageTree.pb:
```
C28144T
T8782C
C14408T
A23403G
C3037T
C1059T
G25563T
G5230T
A21801C,C26456T
G22813T
C23664T,C25904T
A10323G
A22206G,C28253T
A2692T
G23012A,A23063T
C28887T
```

Unfortunately, there's also a "minor branch" with this sequence of mutations, whose path is identical up to the second-to-last node but then diverges:
```
...
A2692T
G23012A,A23063T -- shared up to here
G22206A         -- divergent!  (also a back-mutation for earlier A22206G)
C21614T,G25784T
C28887T         -- same as last node of "major" branch
```
Your B.1.351 example sequences are placed on  that "minor" branch, which is not annotated as B.1.351, so usher keeps working its way back towards root to find a node that is annotated as the root of a lineage, and it hits B.1, so that's the lineage that it assigns.

There's a similar situation with B.1.525, but I'll spare you the even longer sequences of mutations.  :)  (If you really want to dig into it, add `--no-temp` to `pangolin --usher` and see the mutation-paths.txt file generated by usher; compare to clade-paths.txt file created by `matUtils extract -i $(find $CONDA_PREFIX -name lineageTree.pb) -C clade-paths.txt`.)

For B.1.2, there are several branches with permuted order of mutations, none of which has >=60% of B.1.2 representative sequences, so it's not annotated on any node of lineageTree.pb currently and can't be assigned by `pangolin --usher` at all.

I think a more optimal lineageTree.pb would have a single branch for each of those lineages instead of multiple branches.  I hope to work with @rmcolq who builds the COG-UK tree from which lineageTree.pb is extracted to optimize it.  One possibility is the usher package's matOptimize program; there are other optimization methods available including fasttree and iqtree (dev branch) I believe.

Another option under consideration is to add a mode to usher (actually `matUtils annotate`) to annotate a lineage on more than one node/branch in cases like these.

One way or another, we'll find a way to improve the performance of PUSHER, and your input is really helpful and much appreciated!

**Comment by AngieHinrichs** [comment]
I have updated the pangoLEARN repo's [lineageTree.pb](https://github.com/cov-lineages/pangoLEARN/blob/master/pangoLEARN/data/lineageTree.pb) so that it does better now for B.1.525, B.1.351 and the rest of the top 7 items on your list.  It is not yet in a tagged release so updating pangolin will not pull it yet, but here's how to try it out in the meantime:

1. Download lineageTree.pb from https://github.com/cov-lineages/pangoLEARN/blob/master/pangoLEARN/data/lineageTree.pb
2. Assuming the new lineageTree.pb is in your current directory, run pangolin with --usher-tree instead of --usher:
```
pangolin canada_b1351_b1525_examples.fasta --usher-tree lineageTree.pb --outdir pusher_update
```

After running `pangolin --usher-tree` with the updated lineageTree.pb on the 46k Canadian sequences, the top 10 differences are now
```
PLEARN      PUSHER      count
B.1.91      B.1.525       235
B.1.1.121   B.1.1         148
B.1.346     B.1            83
B.1.243     B.1            58
B.1.36.8    B.1.36         57
B.1         B.1.1.318      47
B.1.160     B.1            35
B.1.596     B.1.2          33
B.1.1       B.1            30
B.1.349     B.1            27
```
There's still disagreement for B.1.91 -- but I think B.1.525 is the correct call given the mutations in those sequences, and scorpio/constellations calls cB.1.525 for all 235.  

I will keep working down the list.  Again, thank you for the super-helpful evaluation and test case.

**Comment by fmaguire** [comment]
This is great, I really appreciate the very comprehensive and thorough analysis and fixes!

**Comment by AngieHinrichs** [comment]
The situation for VOCs/VOIs is improved in [release v3.1](https://github.com/cov-lineages/pangolin/releases/tag/v3.1) with @rmcolq's PR #244 which overrides the call from PLEARN/PUSHER if it is not equal to (or a descendant of) the scorpio call lineage.  (It adds a note to the comment column in that case, "scorpio replaced lineage assignment X".)
