### ISSUE TITLE
Keep working on pangolin 2.4.2

### ISSUE THREAD

**Issue by SergioBuenestadoSerrano** [cov-lineages/pangolin#229]
Hi, good morning

This is not really a problem but a query / question. Is it possible to keep working with the previous version (2.4.2) but keep updating the PangoLEARN database?

We have to go to this method since the conda environment where we run our automatic pipeline has some incompatibilities with the new version 3.0.X of pangolin and it is not possible to update the whole environment with the latest version. We are afraid to do "pangolin --update" because it starts using scorpio, constellation and usher, which are the packages that give us these incompatibilities problems.

We want to continue working with pangolin integrated in the automatic pipeline, but we also want to keep the database updated.

Any help or suggestion is welcome.

Thank you so much

**Comment by aineniamh** [comment]
Hi Sergio, if at all possible I'd suggest using the latest version of pangolin, even if it's got more dependencies. It's now able to assign using a designation hash which will have 100% accuracy to the known diversity. The scorpio calls are also really important because for VOCs/VUIs they give an additional piece of information that is likely more reliable than the decision tree inference.

If you really can't update, it should be possbile to just update the pangoLEARN repo using `git+https://github.com/cov-lineages/pangoLEARN.git` and nothing else, but my recommendation would be to update to latest versions.

**Comment by SergioBuenestadoSerrano** [comment]
Hi Aine,

Okay, thank you so much. We will try to create two parallel environments in conda, one to do all the steps of our analysis and an independent one with the latest version of pangolin for lineage assignment.

I hope we can stay up-to-date and don't have any incompatibility issues.

Thank you!

**Comment by aineniamh** [comment]
No worries, hope it works out!
