### ISSUE TITLE
Incorrect Lineage Classification

### ISSUE THREAD

**Issue by santoshe1** [cov-lineages/pangolin#238]
Hello Team,

I am observing some misclassification in lineage assignment for few samples. We see alternate alleles/mutations in the below genes:
aa:S:N501Y
aa:S:H655Y
aa:orf8:E92K

However, they are classified as "A" in the lineage table. Could you let me know what the issue could be?

Pangolin Version - 2.4.2
PangoLEARN Version -2021-05-19

Thank you

**Comment by AngieHinrichs** [comment]
Hi @santoshe1 , S:N501Y has appeared multiple times, even in at least one A sub-lineage.  The same is probably true for other mutations.  If your sequences are in a public repository, and you can share the IDs, then I can take a closer look.  

The latest release of Pangolin ([v3.1](https://github.com/cov-lineages/pangolin/releases/tag/v3.1)) includes a new method, [scorpio](https://github.com/cov-lineages/scorpio)/[constellations](https://github.com/cov-lineages/constellations), that is more accurate for VOCs and VOIs.

**Comment by rmcolq** [comment]
Hi @santoshe1 ! I think this is now probably a pango-designation issue and so am closing it. 
The latest release of pangolin should hopefully solve the problem (especially if your samples are a VOC/VUI). Otherwise, please open an issue here https://github.com/cov-lineages/pango-designation/issues and ideally provide some GISAID accessions/ sequences names  or sequences and we can investigate specific examples further.
