### ISSUE TITLE
Date mismatch between international report and lineage description

### ISSUE THREAD

**Issue by ftrebien** [cov-lineages/pangolin#243]
The earliest date of lineage B.1.1.7 is 2020-02-07 in the [description list](https://cov-lineages.org/lineage_description_list.html), but 2020-09-09 is the earliest sample date in the [global report](https://cov-lineages.org/global_report_B.1.1.7.html). Is this correct? Why is there a difference? The global report appears to be in agreement with other sources. There is also a mismatch between the earliest date in the description list and the earliest sample date in the global reports of [B.1.351](https://cov-lineages.org/global_report_B.1.351.html) and [P.1](https://cov-lineages.org/global_report_P.1.html).

**Comment by aineniamh** [comment]
Ah, we have QC that curates the GISAID data for the global report because we know when the lineage first arose. There's a lot of sequences from 2021 that have been mis-labelled as 2020 on GISAID so have a gate in place for the global report. The lineages pages just display the GISAID data as is, which includes the cases like this that must be a result of mislabelling (i.e. 2020-02-07 should be 2021-02-07).

**Comment by ftrebien** [comment]
@aineniamh Thank you for the clarification!
