### ISSUE TITLE
Potential incorrect assignment of B.1.526.1

### ISSUE THREAD

**Issue by shelby-bennett** [cov-lineages/pangolin#251]
Hello, 

I have noticed potential incorrect lineage assignment of a couple of samples that were previously classified as B.1.526.1. With the most recent update (v3.1.1), they are now being classified as B.1.526. All three of these samples have  characteristic mutations seen in B.1.526.1 that are not present in B.1.526. In particular, S:L452R, S:F157S, S:D614G,S:T859N,S:D950H were present in all three samples with S:D614G being the only shared Spike mutation.

For reference versions used were: 
pangolin 3.1.1
pangoLEARN 2021-06-15
pango-designation v1.2.13

I have also attached a multi-fasta containing the 3 problem sequences if needed. 
[pango_dif_b15261.txt](https://github.com/cov-lineages/pangolin/files/6664564/pango_dif_b15261.txt)

Please let me know if you need any other information!

**Comment by aineniamh** [comment]
Hi @shelby-bennett, there was a recent discussion on pango-designation about these lineages and sublineages have since been merged into the parent: https://github.com/cov-lineages/pango-designation/issues/45

I think this is the desired output as sublineages were not being robustly distinguished and from an epidemiological point of view seem to have very similar properties. Hope this helps clear it up!

**Comment by shelby-bennett** [comment]
@aineniamh Thank you! This definitely clears things up.
