### ISSUE TITLE
Could pangolin conda install wihtout needing git?

### ISSUE THREAD

**Issue by grovesn** [cov-lineages/pangolin#258]
We would like to use pangolin as part of our routine analysis for any "unclassified" genomes when we are looking at the VOC/VUI calls each day.
However, we can't install pangolin because to platform hosting the sequence data is locked down and cannot clone from github.

Is there any way it can be packaged so that it doesn't need to fetch from git? 
(I'm sure you have bigger priorities but just thought I'd ask!)

**Comment by rmcolq** [comment]
I think the answer depends what you mean - I am able to install pangolin from within a conda environment file in my external pipeline in the same way that pangolin installs some of it's dependancies, via git by including e.g: 
```
- pip:
      - git+https://github.com/cov-lineages/pangolin.git
 ```
 (and the rest of the dependancies as in pangolin environment file).
However to assign lineages that remain meaningful over time pangolin receives regular updates to pangoLEARN/usher model file in order to remain accurate as sequences evolve and new lineages emerge. Instead of using `pangolin --update` you could perform a conda environment update.

However if no git at all, I think there might be too many dependancies which are all regularly updated for this (although those who know better than me can correct me). An alternative possibility would be to try and create a bioconda package for just `scorpio` https://github.com/cov-lineages/scorpio which only does VOC/VUI calling and you could keep/create the required constellation files and `reference.json` locally (the defaults are avaliable via git clone https://github.com/cov-lineages/constellations, but command line parameters can avoid this if the info is local).

**Comment by grovesn** [comment]
Thanks! That's really useful.
The issue we have is that the platform we run our analyses on within PHE is not able to use git clone from GitHub (only from the institution based git repos) so any installations that require this fail.
We are just trying out some slight workarounds to see if we can get it working but useful to know that basically it would be a pain!

**Comment by aineniamh** [comment]
Hi @grovesn, I know that we have a GitHub actions that automagically pushes a new docker image to docker hub every time a new release is tagged. I think it could be possible to set up something similar for the cov-lineages repos (pangolin, scorpio, pangoLEARN and constellations) that would push a new conda recipe to the cloud. We can have a look into that and would be happy to have a github actions doing that (I don't currently know how to do it, but feel like it should be possible).

**Comment by grovesn** [comment]
That would be amazing!
We would obviously be happy to help if needed or be available for testing!

**Comment by aineniamh** [comment]
@grovesn, I meant to reply to this before- I believe that there is an external group that _has_ put pangolin and all dependencies on bioconda.

Here: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pangolin/meta.yaml

 I've tried installing it and there's an unsatisfyable error, but it's passing bioconda tests, so it could be just on my end

```
(test_end) [9:15:46] ~/repositories/pangolin % conda install pangolin -c bioconda
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                       

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**Comment by corneliusroemer** [comment]
Do you want to add this to the installation docs? Makes sense to have a
good command ready made!
