### ISSUE TITLE
Feature Request/Query: De-aliased lineage assignments

### ISSUE THREAD

**Issue by fmaguire** [cov-lineages/pangolin#261]
Hey,

As the lineages have gotten deeper and we are using more aliases sometimes its easy to miss nested sets of assignments when doing automated summaries e.g., B.1.617.2 and AY.1/AY.2.  I've just been de-aliasing lineage assignments (e.g., AY.1 to B.1.617.2.1) to using the pango designation repo alias key whenever I've needed for tallying/report summaries.
 
Aliased lineages are definitely more human-readable but the full lineage path makes computational analysis easier.

In light of this I was wondering if there would be interest in a PR to (optionally) add a "de-aliased" lineage assignment column to the pangolin output?   This would have the benefits of making sure the right aliases are used for the lineage assignments in that run.   

No worries if not or that you think this would add too much clutter to the output.  Happy to leave things as a stand-alone script in that case.

As ever thanks for all your amazing work on pangolin!

**Comment by aineniamh** [comment]
Hi @fmaguire, I'd be happy to provide this or something similar! I think we would want to steer clear of calling it a 'lineage' because AY.1 is the official lineage name, so we wouldn't want to cause confusion or encourage anyone to use B.1.617.2.1. I could have it as a flag potentially, where it's an optional column output?
