### ISSUE TITLE
Clarification on what  --update does

### ISSUE THREAD

**Issue by quaeler** [cov-lineages/pangolin#303]
Hello -

I'm trying to determine what the `--update` [functionality](https://cov-lineages.org/resources/pangolin/updating.html) may change. Does this update only alter a database store, or does it potentially also update code functionality within Pangolin?

Can we assume that if there have been no repository changes [here](https://github.com/cov-lineages/pango-designation) that `--update` will not make any alterations to the local definitions?

Similarly, if update does potentially include code functionality changes, can we assume that if we updated at time A, and there have been no GitHub repository changes in this repository since then, that `--update` will not make any code-based changes?

Also, related to major v. minor changes cited in the update document, do you have a document that describes what types of changes merit a major versioning?

Thanks for your work.

**Comment by fmaguire** [comment]
`--update` checks the version release of [pangolin](https://github.com/cov-lineages/pangolin/releases), [pangoLEARN](https://github.com/cov-lineages/pangolearn/releases), [scorpio](https://github.com/cov-lineages/scorpio/releases), [constellations](https://github.com/cov-lineages/constellations/releases) and [pango-designation] (https://github.com/cov-lineages/pango-designation/releases) (for the aliases).
 
 For each of these, if a newer release has been created (major, minor, or patch level), it will be updated to that release. Otherwise it will do nothing.
 
 If you just want to update the data dependencies (i.e., constellations, pangoLEARN, and pango-designation) and not change any of the execution code (scorpio and pangolin) then you can use `--update-data`.

**Comment by quaeler** [comment]
Great - thank you for the information.

**Comment by quaeler** [comment]
Sorry to be a pest, but is there a version number, or date, associated to the updated data that i can ask Pangolin for?

(ie. if i were to ask Pangolin for the version of the data dependencies today, it would say X, and then after a dependency changing `--update-data`, Pangolin would report Y (presumably where Y > X).)

Thanks again.

**Comment by fmaguire** [comment]
`pangolin --all-versions` will display all dependency versions currently installed.

If you want to install a specific release instead of the latest releases for a given dependency you can directly use `pip install`  and a specific release tag from your conda env e.g. `pip install git+https://github.com/cov-lineages/pangolearn@2021-07-09`  (although no guarantees that very divergent versions of dependencies will all still work).

**Comment by quaeler** [comment]
Thank you again!
