### ISSUE TITLE
Version info question

### ISSUE THREAD

**Issue by baileyglen** [cov-lineages/pangolin#310]
Sorry if this has been addressed elsewhere. 
I am using the docker version of pangolin and am confused about the implications off the various data versions. In particular, I am wondering what the implications are of using the pango-designation that is more recent than the pangolearn version. For instance:
```
pangolin: 3.1.11
pangolearn: 2021-08-24
constellations: v0.0.15
scorpio: 0.3.12
pango-designation used by pangoLEARN/Usher: v1.2.66
pango-designation aliases: 1.2.76
```
For instance, pango-designation v1.2.66 contains delta sublineages up to AY.25, but v1.2.76 goes up to AY.32. How are the new designations handled by pangolearn and pangolin in this situation?

**Comment by rmcolq** [comment]
The first pango-designation label refers to which release is used for the latest model files. This is the one which is output in the version labels in pangolin output (e.g. PANGO-v1.2.66) i.e. this is the version number for ALL lineage assignments.
A requested feature of pangolin was to be able to access the aliases directly with a command line flag (e.g. AY=B.1.617.2). We do this by pulling/installing the pango-designation repository directory. Since aliases do not get reassigned (only new aliases defined), having these alias definitions slightly ahead of those seen in assignments is not problematic.
