### ISSUE TITLE
Likely mis-assignment of AY.4.2 lineage call to Epsilon like sequences

### ISSUE THREAD

**Issue by jacaravas** [cov-lineages/pangolin#341]
The latest pangolin/PLEARN/Constellations files are producing likely erroneous AY.4.2 lineage calls for sequences collected Jan - Feb 2021.  Scorpio call for these lineages is "Epsilon (B.1.427/429-like)".  These sequences lack the "HV" mutation.

Known affected sequences:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mqi4/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mqi4/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

covv_virus_name | primary_collection_date | lineage | scorpio_call
-- | -- | -- | --
hCoV-19/USA/CA-CDPH-2000028576/2021 | 2021-01-18 00:00:00 | AY.4.2 | Epsilon (B.1.427/429-like)
hCoV-19/USA/CA-CDC-QDX21613322/2021 | 2021-01-31 00:00:00 | AY.4.2 | Epsilon (B.1.427/429-like)
hCoV-19/USA/CA-CDC-QDX23009347/2021 | 2021-03-14 00:00:00 | AY.4.2 | Epsilon (B.1.427/429-like)
hCoV-19/USA/CA-CDPH-2000033170/2021 | 2021-01-26 00:00:00 | AY.4.2 | Epsilon (B.1.427/429-like)
hCoV-19/USA/CA-SEARCH-11724/2021 | 2021-02-04 00:00:00 | AY.4.2 | Epsilon (B.1.427/429-like)
hCoV-19/USA/CA-CZB-23359/2021 | 2021-01-14 00:00:00 | AY.4.2 | Epsilon (B.1.427/429-like)
hCoV-19/USA/CA-SEARCH-16893/2021 | 2021-02-08 00:00:00 | AY.4.2 | Epsilon (B.1.427/429-like)
hCoV-19/USA/CA-SEARCH-11217/2021 | 2021-02-24 00:00:00 | AY.4.2 | Epsilon (B.1.427/429-like)
hCoV-19/USA/CA-CDC-QDX23355429/2021 | 2021-03-21 00:00:00 | AY.4.2 | Epsilon (B.1.427/429-like)
hCoV-19/USA/CA-CDC-QDX22786691/2021 | 2021-03-09 00:00:00 | AY.4.2 | Epsilon (B.1.427/429-like)
hCoV-19/USA/CA-CDC-QDX22634018/2021 | 2021-03-03 00:00:00 | AY.4.2 | Epsilon (B.1.427/429-like)
hCoV-19/USA/WA-UW-61898/2021 | 2021-02-05 00:00:00 | AY.4.2 | Epsilon (B.1.427/429-like)

</body>

</html>

Installed software versions:
	PLEARN date: 2021-10-18
	PLEARN version: PANGO-v1.2.88, PLEARN-v1.2.88
	Pango version: v1.2.88
	Pangolin version: 3.1.16
	Scorpio version: 0.3.14

**Comment by AngieHinrichs** [comment]
I would have expected scorpio to override the pangoLEARN call in pangolin lineage_report.csv output, but I see it's getting just "B.1" in the second column:

| taxon | lineage | conflict | ambiguity_score | scorpio_call | scorpio_support | scorpio_conflict | version | pangolin_version | pangoLEARN_version | pango_version | status | note |
|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| hCoV-19/USA/CA-SEARCH-16893/2021 | B.1 | 0.0 | 1.0 | Epsilon (B.1.427/429-like) | 1.000000 | 0.000000 | PLEARN-v1.2.86 | 3.1.15 | 2021-10-13 | v1.2.86 | passed_qc | scorpio call: Alt alleles 11; Ref alleles 0; Amb alleles 0; Oth alleles 0 |

I don't see AY.4.2 in lineage_report.csv... ah, are you using --no-temp and looking at pangolearn_assignments.csv ?

Those sequences all cluster together in the UCSC/UShER tree, with other Epsilon sequences, and they have C7851T (ORF1ab:A2529V) in common (which happens to be the AY.4 defining mutation... not AY.4.2 though):

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pangolin-341.json?branchLabel=nuc%20mutations&label=nuc%20mutations:C22591T,C25614T

pangolin --usher assigns B.1.429.

**Comment by jacaravas** [comment]
Hi Angie,
We're getting that call from the "pangolin --outfile" file.  We aren't running usher.  The only other parameters we are providing besides "--outfile" are "--tempdir" and "--threads"

**Comment by AngieHinrichs** [comment]
Ah, sorry, since running `pangolin --update` again this morning now I see AY.4.2 is assigned not B.1.  

@rmcolq is there a recent change that would make Scorpio's call of Epsilon not override pangoLEARN's call of AY.4.2 for these pretty clearly Epsilon sequences?

| taxon | lineage | conflict | ambiguity_score | scorpio_call | scorpio_support | scorpio_conflict | version | pangolin_version | pangoLEARN_version | pango_version | status | note |
|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| hCoV-19/USA/CA-SEARCH-16893/2021 | AY.4.2 | 0.0 | 1.0 | Epsilon (B.1.427/429-like) | 1.000000 | 0.000000 | PLEARN-v1.2.88 | 3.1.16 | 2021-10-18 | v1.2.88 | passed_qc | scorpio call: Alt alleles 11; Ref alleles 0; Amb alleles 0; Oth alleles 0 |

**Comment by AngieHinrichs** [comment]
And @jacaravas, have you considered running --usher?  Were there any barriers to trying or using it?

**Comment by rmcolq** [comment]
This is a tricky case. Epsilon is the only constellation which scorpio does not override because there is one constellation file for it, and it doesn't have an `mrca_lineage` because that would not make sense. It didn't seem to be a problem before, but if we are getting cross calls with AY.4.2 and Epsilon, then we should revisit. I have made updates to scorpio which should allow multiple constellation files for the same constellation, so in theory it is now possible to separate Epsilon out into 2 files. Scorpio v0.3.15 fixed a problem with `scorpio list` which pangolin depends on to remove false positives in some cases. With that fixed I would expect pangolin to assign "None" in this case rather than the false positive AY.4.2

**Comment by aretchless** [comment]
Hi Rachel (@rmcolq). It might be simpler to focus on the removal of the false positive rather than on reassigning to Epsilon (I say this without knowing anything about the specific code, of course). Conceptually, it seems like a 'not AY.4.2' call from scorpio should have the same effect on AY.4.2 lineage assignment, regardless of any other constellation that scorpio might detect.  Focusing purely on the false positive removal could assure consistency there, without getting caught up in how easy/difficult it is to define other lineages. Just my two cents. Thanks for working on this.

**Comment by DOH-SML1303** [comment]
The latest pangolin update is calling a B.1.429 sequence as AY.4.2 I have one sequence that is being called AY.4.2 by the newest pangolin update but does not contain any of the mutations. seq USA/WA-61898/2021


taxon | lineage | conflict | ambiguity_score | scorpio_call | scorpio_support | scorpio_conflict | version | pangolin_version | pangoLEARN_version | pango_version | status | note
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
hCoV-19/USA/WA-UW-61898/2021\|EPI_ISL_1341416\|2021-02-05 | AY.4.2 | 0 | 0.970708283313325 | Epsilon (B.1.427/429-like) | 1 | 0 | PLEARN-v1.2.88 | 3.1.16 | 2021-10-18 | v1.2.88 | passed_qc | scorpio call: Alt alleles 11; Ref alleles 0; Amb alleles 0; Oth alleles 0




mutations
Spike D614G, Spike L452R, Spike S13I, Spike W152C, N T205I, NS3 Q57H, NS3 V228A, NSP2 T85I, NSP3 A1711V, NSP9 I65V, NSP12 N734Y, NSP12 P323L, NSP12 V588L, NSP13 D260Y
