### ISSUE TITLE
Documentation of lineage assignment process (scorpio and pangolearn)

### ISSUE THREAD

**Issue by aretchless** [cov-lineages/pangolin#343]
Hello. I have not been able to find clear documentation of how the pangoLearn and scorpio calls (and hash checking) are merged to produce a final lineage assignment by pangolin (when using default parameters). I think that I understand the process, based on the release notes and various discussions, but I've found it very hard to explain to others without an authoritative reference for the process. A reference document would also help me to report bugs, since I would have greater confidence that I understand what the intended output is. A flowchart would be ideal.

For what it's worth, here's my rough understanding of the process (and my questions):

1. Check sequence hash. If sequence is designated, assign that lineage.
2. Otherwise, run pangoLearn to provide preliminary assignments (or usher, if this option is selected)
3. Run scorpio. What are the conditions where this overwrites the assignment? Is it only pangoLearn, or hash also? Does the constellation require a certain parameter to be set? What are the conditions when an assignment is removed due to a negative scorpio call? 

Thanks.

**Comment by fmaguire** [comment]
Yeah that is the process, you can use snakemake to directly dump the DAG of the assignment process if it helps to see it/summarise it visually:

![PangoLEARN mode](https://user-images.githubusercontent.com/1698629/139869484-fe8b6abf-92df-4032-b23f-3ea47a3d6130.png)

![USheR mode](https://user-images.githubusercontent.com/1698629/139869493-c4b52663-1094-477d-b43d-5899dad27a45.png)

If a genome is assigned by hash everything else (pangolearn/usher AND scorpio) is skipped and it is directly entered into the output report with the note: "Assigned from designation hash".

With scorpio 4 things can happen that determine the final reported lineage assignment:
1. **Model-assigned (i.e., pangoLEARN or UShER) lineage is congruent with scorpio assignment (i.e., model-assigned lineage is same or nested within the scorpio assignment)**: the model-assigned lineage is reported with the note containing scorpio alt/ref information.
2. **Model-assigned lineage is not congruent with scorpio assignment**: model-assigned lineage is replaced by the scorpio assignment (and reported as the lineage assignment) with the note "scorpio replaced lineage assignment X". 
3. **Model-assigned lineage is a lineage that is "incompatible" with the scorpio call**: model-assigned lineage is replaced by the scorpio assignment (and reported as the lineage assignment) with the note "scorpio replaced lineage assignment X". This incompatibility is defined in the [constellations directly](https://github.com/cov-lineages/constellations/blob/0d9c7408466e2f3ec75893d67213fac3a9938d32/constellations/definitions/cB.1.617.2.json#L16) and is for cases where say the model has assigned AY.4.2 but scorpio can't detect the defining mutations for such a specific assignment and has assigned to basal B.1.617.2. These are still nested assignments so would otherwise be congruent with the model-assignment but are being explicitly checked.
4. **Model-assigned lineage has a constellation but there was no scorpio assignment**: model-assigned lineage is replaced with "None" and no lineage is reported  with the note "lineage assignment X was not supported by scorpio".

I think that covers everything although @aineniamh or someone will be able to correct me if I've got anything incorrect.

**Comment by AngieHinrichs** [comment]
Awesome, thanks @fmaguire!  I think there's at least one more special case, although it might go away in the foreseeable future.  In cov-lineages/pangolin#341 @rmcolq mentioned an [exception for Epsilon](https://github.com/cov-lineages/pangolin/issues/341#issuecomment-954977038): Scorpio currently does not override incongruent pangoLEARN/usher for Epsilon because (if I'm interpreting Rachel's comment about `mrca_lineage` correctly) Epsilon encompasses two lineages (B.1.427 and B.1.429) for which the Pango system does not have a specific common ancestor (just B.1 which is way too broad).  However, it sounds like that might change because @rmcolq added an issue in constellations: https://github.com/cov-lineages/constellations/issues/34 ?

**Comment by fmaguire** [comment]
Ah yes, I meant to follow up on what [this bit of logic](https://github.com/cov-lineages/pangolin/blob/master/pangolin/scripts/pangolearn.smk#L253) was doing but forgot! As @AngieHinrichs says currently if the scorpio assignment contains a `/' (only impacting Epsilon) then *2* occurs.

**Comment by aretchless** [comment]
Thank you Finlay and Angie. That's very helpful.

**Comment by fmaguire** [comment]
This this would help in the documentation to make this even clearer?

![](https://user-images.githubusercontent.com/1698629/139964427-cd09d15d-302a-4be1-8ad7-9bca623ffceb.png)

**Comment by aretchless** [comment]
Hi. I may have closed this issue prematurely, and would appreciate some feedback from the development team or website maintainers. It would help us (CDC) a lot if we could point our collaborators to an 'official' and explicit description of the process for assigning lineages. I wouldn't even know where to start with proposing an edit to the documentation.

**Comment by rmcolq** [comment]
The above (as written and edited by Finlay) is an excellent summary of the process

**Comment by bede** [comment]
@fmaguire Thank you for this succinct and illuminating summary! I have a related simple question:

> Genome assigned by hash: everything else (pangolearn/usher AND scorpio) is skipped and hashed lineage **is reported with the note: "Assigned from designation hash".**

Where is this note displayed? The note column of the CSV or stderr? 

An AY.4.2 sequence of ours is generating empty `ambiguity_score` and `scorpio_call` columns with 3.1.16, but neither the note column nor stderr indicate that it was assigned by hash as you suggest. Is this implicit?

end of stderr:
```
No sequences to assign with pangoLEARN.
complete 11/12/2021, 11:22:20
Output file written to: lineage_report.csv
```

**Comment by aretchless** [comment]
@bede. The version field will have "PANGO" written in it if the sequence was assigned from the sequence hash.
https://cov-lineages.org/resources/pangolin/output.html

**Comment by bede** [comment]
Ah yes, had forgotton, thanks @aretchless !

**Comment by aineniamh** [comment]
Just to follow up- for pangolin 4.0 (set to be released today), I've made a [workflow diagram](https://cov-lineages.org/resources/pangolin/pipeline.html) which may help show the steps in the updated assignment process. I'll continue to add more details to that page as any changes come about in future.
