### ISSUE TITLE
Can't update pango-designations

### ISSUE THREAD

**Issue by enabieva** [cov-lineages/pangolin#349]
I seem to be unable to update pango-designations to the newest version when using standalong command-line pangolin.
After following the instructions for updating, both via pangolin --update and using the "major update" scenario, I get:
% pangolin -dv
pango-designation v1.2.93 used for pangoLEARN and UShER training, alias version 1.2.98

I don't understand what "alias version" is, but when I run pangolin, it assigns lineages according to v1.2.93

What am I doing wrong and how can I get the newest version (1.2.98)?

**Comment by theosanderson** [comment]
You aren't doing anything wrong :) . There is a period of time between lineages being designated, and those designations being used to train a model that is released for use in Pangolin. You can see the latest model released at https://github.com/cov-lineages/pangoLEARN/releases , which was trained using the v1.2.93 designations

**Comment by enabieva** [comment]
Thank you!  But is there any way to get sequences annotated with the new designations (v.1.2.96+)?  If I understand correctly, the Usher model does not need to be trained.

**Comment by AngieHinrichs** [comment]
pangolin --usher uses a tree instead of a trained model, but the tree still requires some annotation before new lineages can be assigned using it.  The tree used by pangolin --usher is [lineageTree.pb](https://github.com/cov-lineages/pangoLEARN/blob/master/pangoLEARN/data/lineageTree.pb) in the pangoLEARN repository.  pangoLEARN releases use the same pango-designation version for both the trained model and lineageTree.pb, to avoid confusion about what lineages should appear in results from each release.

The UCSC/UShER tree in the [UShER web interface](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace) tends to be updated sooner with new lineages, although I am a few days behind at the moment and the latest tree has only v1.2.96 of pango-designation.  You can upload sequences (or if they are already in the tree, you can paste in names or accessions), view subtrees in Nextstrain, and in the Color By dropdown, choose 'Pango lineage assigned by UShER'.

**Comment by enabieva** [comment]
@AngieHinrichs , thank you very much.  Now I understand what's going on.
