### ISSUE TITLE
Misclassification: Alpha / B.1.1.7

### ISSUE THREAD

**Issue by philiptzou** [cov-lineages/pangolin#364]
It seems EPL_ISL_2650990 has most of the signature B.1.1.7 mutations but it is classified as B.1.1 (pangolin: 3.1.17; pangoLEARN: 2022-01-20). Similar issues found for EPI_ISL_2650701, EPI_ISL_2650621, EPI_ISL_2650820, EPI_ISL_2650965, EPL_ISL_2650990, etc.

[EPI_ISL_2650990](https://github.com/cov-lineages/pangolin/files/7974111/EPI_ISL_2650990.fas.txt) (Pango calls B.1.1):

<img width="1331" alt="Screen Shot 2022-01-31 at 12 33 59 PM" src="https://user-images.githubusercontent.com/809865/151868737-6cb5a2f9-f886-414b-b112-fe84fd0764ae.png">

[EPI_ISL_7711465](https://github.com/cov-lineages/pangolin/files/7974144/EPI_ISL_7711465.fas.txt) (Pango calls A.2.5.1):

<img width="1332" alt="Screen Shot 2022-01-31 at 12 46 11 PM" src="https://user-images.githubusercontent.com/809865/151870390-eae89b43-92fc-4769-aa7d-178b16c86a9e.png">

[EPI_ISL_4093662](https://github.com/cov-lineages/pangolin/files/7974665/EPI_ISL_4093662.fas.txt) (Pango calls P.1):

<img width="1274" alt="Screen Shot 2022-01-31 at 2 33 56 PM" src="https://user-images.githubusercontent.com/809865/151884215-4c6d0a42-8323-44f4-991e-4511e63faa58.png">

All above should be Alpha according to [Outbreak.Info's consensus mutation list](https://outbreak.info/situation-reports/alpha).

**Comment by philiptzou** [comment]
@rmcolq Thanks for the response! No, those sequences are not very recent. I found them from discordances from the comparison between Pangolin and our [Spike genotyper](https://github.com/hivdb/sierra-core/tree/ec06bdc72d89ca5aac17540322cc5c63761113a3/src/main/java/edu/stanford/hivdb/genotypes). Thanks for providing the explanation and fixed the P.1 classification.

**Comment by rmcolq** [comment]
Just extending on this before I close the issue, for sequences like these (slightly lower quality/more ambiguous), we would recommend using the `--usher` mode (which will become default in the next major pangolin release). For your examples, in usher mode, you would get a lineage assignment of "None" for all 3 sequences due to the sequence qualities (therefore avoid the wrong A lineage assignment by pangoLEARN), but you would also get a note about where they each fell on the usher tree which does say that they most likely fall within B.1.1.7 clade.
