### ISSUE TITLE
What's the meaning of "Omicron (Unassigned)"

### ISSUE THREAD

**Issue by geocarvalho** [cov-lineages/pangolin#367]
Hello team, thanks for the nice work.
I have found some cases this week where you can find this `None` assigned as lineage and `Omicron (Unassigned)` for scorpio call. 

```
taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,version,pangolin_version,pangoLEARN_version,pango_version,status,note
sample1,None,0.0,0.7603219942871982,Omicron (Unassigned),0.666700,0.000000,PLEARN-v1.2.123,3.1.19,2022-01-20,v1.2.123,passed_qc,scorpio call: Alt alleles 26; Ref alleles 0; Amb alleles 13; Oth alleles 0; scorpio replaced lineage assignment BA.1.1
```

The data looks good, so any idea about it?

Thanks.

**Comment by rmcolq** [comment]
It means that the quality of the sequences was not sufficient for a confident Omicron lineage classification, but was sufficient to be clear that the sequence was an Omicron. In the example provided, there were 26 alt alleles and 13 ambiguous bases at defining sites for the 'parent lineage' B.1.1.529 so we can be confident that it is Omicron. However this is not a true lineage - the true lineages are its 'children' BA.1, BA.2 and BA.3. Due to ambiguous bases (or ref alleles) it was unclear which if these it should be classified as.

**Comment by geocarvalho** [comment]
Thank you @rmcolq
