### ISSUE TITLE
Are there stickers for your logo(s)?

### ISSUE THREAD

**Issue by klsheridan** [cov-lineages/pangolin#375]
Clearly a very important inquiry. If these stickers do, in fact, exist.... can we buy some?

-Krystal

**Comment by aineniamh** [comment]
So, technically yes- because in a fit of procrastination about a year ago I made a [redbubble](https://www.redbubble.com/i/sticker/pangolin-by-aineotoole/64507291.EJUG5) account. But they set the prices and to get a sticker from them is pretttty steep (by the way you can also get t-shirts, mugs, bedspreads and shower curtains, which I find very funny). If you know of another sticker place that is more reasonably priced I am happy to set one up too!
