### ISSUE TITLE
Update to version 4 issue with faToVcf -includeNoAltN

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [cov-lineages/pangolin#394]
Hi,
Great work. I just updated to version 4 of pangolin and the faToVcf -includeNoAltN in the usher step didn't work. I had to download it from ucsc directly http://hgdownload.cse.ucsc.edu/admin/exe/ and put the downloaded version into the PATH of the environment. faToVcf has no version flag so it wasn't immediate obvious. 

Just putting it here in cases others have the same issue.

**Comment by AngieHinrichs** [comment]
Hi @BenjaminSchwessinger, thanks for posting the workaround!  Unfortunately, for a major version change like v3 -> v4, `pangolin --update` is insufficient because there are conda environment changes, not just updates to the pangolin code.  For example, in the [v4 environment.yml](https://github.com/cov-lineages/pangolin/blob/98c871f45fd541b3ab4565f3c4429371c6b72ad2/environment.yml#L14) file, faToVcf now has a minimum conda version (`ucsc-fatovcf>=426`) -- and even more importantly, there is a new repository dependency [pangolin-data](https://github.com/cov-lineages/pangolin-data) that replaces the pangoLEARN and pango-designation repositories.

So for major updates, it's best to use conda to update pangolin instead of `pangolin --update`.  Instructions are here:

https://cov-lineages.org/resources/pangolin/updating.html

**Comment by BenjaminSchwessinger** [comment]
Great thanks @AngieHinrichs. We just have an automatic update in our script to always fetch the latest versions of pangolin hence this issues I think. I updated everything now as recommended as well from the repo as conda https://anaconda.org/bioconda/pangolin is still at version v3.1.20. Worked like a charm as well.

**Comment by AngieHinrichs** [comment]
Great, thanks for confirming @BenjaminSchwessinger!  I bet a lot of scripts include `pangolin --update`.  @fmaguire had a good suggestion to make `pangolin --update` check for major version change, and warn instead of doing a partial update that won't work!
