### ISSUE TITLE
Is ambiguity_score applicable for USHER results or only for pangoLEARN ?

### ISSUE THREAD

**Issue by KartofellSalat** [cov-lineages/pangolin#423]
It may look like a silly question but I noticed that when running pangolin with USHER the `ambiguity_score` is always an empty string. Does this means that this field is not to be considered when using USHER or is that synonym of ambiguity_score = 0 ?

Thank you ;)

**Comment by AngieHinrichs** [comment]
Not a silly question, but a good reminder that we should update the [documentation](https://cov-lineages.org/resources/pangolin/output.html).  You're right, ambiguity_score is specific to pangoLEARN.  There is also a conflict column which is populated for both pangoLEARN and UShER.  For UShER, it is the number of equally optimally parsimonious placements (EPPs) that disagree with the assigned lineage divided by the total number of EPPs.  

Most of the time, there is only one EPP, so the conflict is 0 -- no disagreeing placements.  In that case the comment column should have something like `Usher placements: BA.2(1/1)`.

It is also common to have multiple EPPs, but for the same lineage, in which case the comment column has something like `Usher placements: BA.2(2/2)`.  The conflict is still 0 because there are no EPPs that disagree with the assigned lineage.

However, when a sequence has a lot of Ns or ambiguous base calls, there may be multiple EPPs in different lineages, for example `Usher placements: BA.1(4/6) BA.1.1(1/6) BA.1.15(1/6)`.  BA.1 is assigned because it has the most EPPs, but 2 out of 6 EPPs disagree with that, so the conflict is 2/6 = 0.33333.

**Comment by KartofellSalat** [comment]
I see, thanks a lot for this explanation !
