### ISSUE TITLE
Pango web application not displaying latest Pangolin version

### ISSUE THREAD

**Issue by jemstone78** [cov-lineages/pangolin#424]
I noticed that the Pangolin web application is still displaying version 3.1.20 from 2-28-2022, and saw the release notes for Pangolin v4.0 and that the web application would also similarly experience an update. Is the web application going to be updated soon for the newest Pango version? Thanks

**Comment by CorinY** [comment]
Hi @jemstone78, the website will be updated but I can't give an exact timeline for now. There are a few more checks and changes we have to make compared to a normal update. It may also be a good time to clear out some technical debt, putting the site on a more robust and sustainable footing for the future.

I'll announce back in this thread when it's done.

Best wishes,
Corin

Senior Research Software Engineer  
[Centre for Genomic Pathogen Surveillance](https://www.pathogensurveillance.net/)  
[Big Data Institute, Oxford University](https://bdi.ox.ac.uk)

**Comment by AngieHinrichs** [comment]
That's great @CorinY!  I'd just like to check regarding the data version though: [2022-04-09](https://github.com/cov-lineages/pangoLEARN/releases/tag/2022-04-09) is a release of the pangoLEARN repository which was a dependency of pangolin v3, and is still in place for use by pangolin v3 installations.  But in [pangolin v4.0](https://github.com/cov-lineages/pangolin/releases/tag/v4.0), the data dependencies changed.  Now, instead of the pangoLEARN and pango-designation repositories, pangolin v4 uses [pangolin-data](https://github.com/cov-lineages/pangolin-data) for which the latest release is [v1.3](https://github.com/cov-lineages/pangolin-data/releases/tag/v1.3).  

In case it's relevant to the web app's installation of pangolin (?), for minor updates (e.g. v3.0 to v3.1), `pangolin --update` is usually sufficient to update the installation.  However, for major updates (v3 to v4), a full conda environment update is required in order to pick up new dependencies like pangolin-data.  Instructions for bioconda and development installations are here:  https://cov-lineages.org/resources/pangolin/updating.html

**Comment by CorinY** [comment]
Hi @AngieHinrichs, I think it's just a problem with how we're handling the version information. The values that appear on the site are entered manually, and I still need to update that side of things. It's definitely Pangolin 4.0.5 and I see PANGO-v1.3 in the version field. Since everything is wrapped in docker we rebuild from scratch for every release, so at least in theory we shouldn't run into update issues. It would be good to catch up (after Easter) on adding the new information and changes to the website, and check I get everything in.
