### ISSUE TITLE
Pangolin --datadir with Usher

### ISSUE THREAD

**Issue by tjdurant** [cov-lineages/pangolin#458]
Hello and apologies for this not being an "issue" per say, but I thought that others might have trouble with this as well.

When running pangolin in some settings, we need to version lock the software and the data dependencies to maintain between-run consistency, as I'm sure others aim for as well.

Prior to the v4.x update we were maintaining local snapshots of the pangolin data dependencies (e.g., pangoLEARN, pango-designation, and constellations) on our servers. 

My question is, with the recent update, do we need to specify anything for Usher in the --datadir parameter? When looking at the documentation, it isn't entirely clear to me what we should be doing for that:
```
-d DATADIR, 
      --datadir DATADIR
                            Data directory minimally containing the pangoLEARN model, header files, 
                            UShER tree and alias file. Default: Installed pangolin-data package.
      --usher-tree USHER_PROTOBUF
                            UShER Mutation Annotated Tree protobuf file to use instead of --usher 
                            default from pangolin-data repository or --datadir.
```

Is there an `UShER Mutation Annotated Tree protobuf file` that we need to put in datadir? 

Any clarification or assistance on this would be very much appreciated.

Thank you,
T

**Comment by AngieHinrichs** [comment]
Hi @tjdurant - good question, and "/issues" is a perfectly reasonable place for it.  :)  

The short answer is that the usher tree is included in pangolin-data so you don't have to do anything special to add it -- but `--datadir` currently does not support rolling back to older data versions.

In general, containers might be a useful way for you to lock in software and data versions; for example, State Public Health Bioinformaticians (StaPH-B) maintains a set of pangolin docker files here:

https://github.com/StaPH-B/docker-builds/tree/master/pangolin

They also have a [README](https://github.com/StaPH-B/docker-builds#readme) and guide.

Another alternative would be to create a separate conda environment for each version (or rather, combination of pangolin, pangolin-data, scorpio, and constellations versions).

`--datadir` as currently implemented is intended to enable updating to the latest version even when the current installation is read-only (for example, if running in a locked-down container, but still wanting to use the very latest released data).  If you run `pangolin --update-data --datadir $datadir`, and the currently installed version of pangolin-data is the latest version already, then pangolin-data is not added to `$datadir` -- the installed latest version will be used.  

However, if `$datadir` contains a version of pangolin-data that is older than the installed version, when you run `pangolin --data-dir $datadir`, the older version will be ignored (!) and the newer installed version will be used instead.

It is possible to construct a datadir that contains older versions; but with the current release of pangolin (v4.0.6) those older versions will be ignored.  In the latest pangolin source code in github (not yet released) there is a new option `--use-old-datadir` that allows older data versions to be used.  But again, that option will only exist in future releases and isn't available in older pangolin versions.

The `--usher-tree` option overrides both `--datadir` and the currently installed pangolin-data's usher tree.  Its primary use is for testing a new usher tree file before release.  It *could* be used to force an older version of an usher tree; however, there is not an equivalent option for constellations, which is very important since scorpio/constellations can override the usher (or pangoLEARN) result.  So that's not a satisfactory solution either.

I hope either the docker containers or conda environments will work for you.
