### ISSUE TITLE
No New Lineages Since March

### ISSUE THREAD

**Issue by Boruchf** [cov-lineages/pangolin#466]
Why are there no new lineages since March?

**Comment by OrsonMM** [comment]
I have the same question, I can check that only Pango-designation is updated. But other tools like scorpio, constellations and pangoLEARN is not.

**Comment by Boruchf** [comment]
Why are there no new COVID19 lineages in Pango since March?

**Comment by AngieHinrichs** [comment]
Sorry about the delays and we hope to provide updates fairly soon.  pango-designation releases [v1.10](https://github.com/cov-lineages/pango-designation/releases/tag/v1.10) and [v1.11](https://github.com/cov-lineages/pango-designation/releases/tag/v1.11) were just tagged 6 days ago and earlier today respectively; @aineniamh will train a new pangoLEARN model and I will make a new lineage tree for UShER mode.  Between training and testing, that process can take a week or two.

pango-designation release v1.9 was tagged on May 13th and pangolin-data was updated to release v1.9 on May 26th.  If you run `pangolin --update-data`, if you already have v1.9 then it will tell you, and if you don't already have v1.9 then it will fetch it and attempt to install it.

Unfortunately it looks like GISAID is still using pangoLEARN v1.8 even for the most recent sequences:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/186983/175132545-2b96cda6-37b8-4eeb-b5dc-e2ba95efe273.png">
So I see how you could get the impression that there have been no new lineages since March!

I have reached out to GISAID regarding updating their use of pangolin.  It would probably help if more registered GISAID users could also ask GISAID to update their pangolin installation.

**Comment by AngieHinrichs** [comment]
@Boruchf are you running pangolin locally to assign lineages to genome sequences, or searching for lineages on GISAID and/or some other website?

**Comment by aineniamh** [comment]
To add, we actually had generated an update for v1.10, but then found an issue with a couple of designations that was resolved in v1.11. This is why v1.10 wasn't released, we decided it was better to just release the updated version. 

I'm going to close this issue as v1.11 was released yesterday, as well as a larger change to pangolin software that in usher mode scorpio calls are no longer overwritten, so I would recommend updating. Thanks for flagging though. 

Áine

**Comment by Boruchf** [comment]
Hi,

I see they've added some more BA.1/BA.2 hybrids. However, they have not added any more earliest dates noted. The last listed date is still March 13 (lineage XW). I'm trying to get some idea about current new Omicron lineages, so I would like to see dates.

Boruch
השג את ‏Outlook עבור Android‏<https://aka.ms/AAb9ysg>
________________________________

**Comment by Boruchf** [comment]
And thanks for your help so far.

Boruch

השג את ‏Outlook עבור Android‏<https://aka.ms/AAb9ysg>
________________________________

**Comment by aineniamh** [comment]
The latest lineages were tagged 8 days ago on pango-designation: https://github.com/cov-lineages/pango-designation/releases/tag/v1.11

But since then the pango team have been adding even more lineages: https://github.com/cov-lineages/pango-designation/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc 

Check the [pango-designation](https://github.com/cov-lineages/pango-designation) repo for the latest lineages described

**Comment by Boruchf** [comment]
No. I just joined to check the rate of new lineage formation. Do you know of a website that has more updated lineages?

Boruch

השג את ‏Outlook עבור Android‏<https://aka.ms/AAb9ysg>
________________________________
