### ISSUE TITLE
pangolin vs nextclade

### ISSUE THREAD

**Issue by fancybeakers** [cov-lineages/pangolin#516]
hi admins, wondering the what is the difference between nextclade and pangolin variant calling. Uploaded one sequence between the two web application but they are pangolin variant calling is different between the two. 
Nextclade seems to be more updated? Showing a sub-variant, while pangolin variant calling seems outdated still showing the parent lineage.
Appreciate your assistance in clarifying the matter

**Comment by aretchless** [comment]
Hello. I am not involved with either project, but I do pay attention to both. The short answer is that each project has its own update schedule and assignment algorithm, so they are not necessarily in sync. In detail:
1. cov-lineages: lineage designations start with the 'pango-designations' repository (https://github.com/cov-lineages/pango-designation); these are bundled into 'releases' every once in a while. The releases then propagate to the 'pango-data' repository, which provides the datasets needed by the pangolin software, which assigns the lineages using the Usher algorithm (by default).
2. nextclade also uses the designations from 'pango-designations', but does not rely on the releases. They may incorporate the new designations before or after pango-data does.  They use a different assignment algorithm, described here: https://docs.nextstrain.org/projects/nextclade/en/stable/user/algorithm/nextclade-pango.html

**Comment by AngieHinrichs** [comment]
Yes, thank you @aretchless, and sorry @fancybeakers about the delayed reply.  nextclade does tend to be updated much more frequently.  Last week there was a new release ([v1.19](https://github.com/cov-lineages/pangolin-data/releases/tag/v1.19)) of pangolin-data, so after you run
```
pangolin --update-data
```
pangolin will be able to assign lineages included in [pango-designation v1.19](https://github.com/cov-lineages/pango-designation/releases/tag/v1.19) (lineages designated through 30 March), if you are using the default usher analysis mode.  (Due to server issues, the pangoLEARN model files have not been updated since pango-designation v1.18.)

**Comment by AngieHinrichs** [comment]
Also, if you continue to see unexpected differences between nextclade and pangolin after updating, feel free to send specific examples and we can look into the differences.  The full UShER tree at UCSC usually has the latest Pango lineages annotated within a few days of designation, so another way to check is to upload sequences to the [UShER web interface](https://usher.bio/) and view the resulting subtrees to see what lineage is indicated by each sequence's placement in the full tree.

**Comment by aineniamh** [comment]
Going to close this issue now as I believe the query has been answered
