### ISSUE TITLE
Error in rule assign_lineage 

### ISSUE THREAD

**Issue by judyssister** [cov-lineages/pangolin#82]
Dear there, 

I have seen your answer to  the question related,  but it cannot help me to solve my problem...

Could you please let me know how to solve this error?

Thanks a lot,

Jing

        Error in rule assign_lineage:
        jobid: 4
        output: /var/folders/yc/b8ybgrf57lv2b3hp_72sdfqh0000gn/T/tmp4bw9w7fz/tax455772tax.txt
        shell:
        
        assign_lineage.py  --separator '_' --index 1         --collapse_to_polytomies 5e-06 --taxon 'tax455772tax'         --input /var/folders/yc/b8ybgrf57lv2b3hp_72sdfqh0000gn/T/tmp4bw9w7fz/tax455772tax.nexus.tree --output /var/folders/yc/b8ybgrf57lv2b3hp_72sdfqh0000gn/T/tmp4bw9w7fz/tax455772tax.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

        Shutting down, this might take some time.
        Exiting because a job execution failed. Look above for error message
        Complete log: /private/var/folders/yc/b8ybgrf57lv2b3hp_72sdfqh0000gn/T/tmp4bw9w7fz/.snakemake/log/2020-07-                        20T095619.857180.snakemake.log

        [Mon Jul 20 09:58:24 2020]
        Error in rule assign_lineages:
        jobid: 0
        output: /Users/yangjing/2019_ncov_beijing/pangolin/lineage_report.csv

        RuleException:
        CalledProcessError in line 75 of /Users/yangjing/opt/anaconda3/envs/pangolin/lib/python3.6/site-        packages/pangolin/scripts/assign_query_file.smk:
        Command 'set -euo pipefail;  snakemake --nolock --snakefile         /Users/yangjing/opt/anaconda3/envs/pangolin/lib/python3.6/site-packages/pangolin/scripts/assign_query_lineage.smk --directory /var/folders/yc/b8ybgrf57lv2b3hp_72sdfqh0000gn/T/tmp4bw9w7fz --configfile /var/folders/yc/b8ybgrf57lv2b3hp_72sdfqh0000gn/T/tmp4bw9w7fz/config.yaml --config outdir=/Users/yangjing/2019_ncov_beijing/pangolin outfile=/Users/yangjing/2019_ncov_beijing/pangolin/lineage_report.csv write_tree=False tempdir=/var/folders/yc/b8ybgrf57lv2b3hp_72sdfqh0000gn/T/tmp4bw9w7fz query_fasta=/var/folders/yc/b8ybgrf57lv2b3hp_72sdfqh0000gn/T/tmp4bw9w7fz/query.fasta qc_fail=/var/folders/yc/b8ybgrf57lv2b3hp_72sdfqh0000gn/T/tmp4bw9w7fz/query.failed_qc.fasta representative_aln=/var/folders/yc/b8ybgrf57lv2b3hp_72sdfqh0000gn/T/tmp4bw9w7fz/anonymised.aln.fasta lineages_version=2020-05-19 guide_tree=/Users/yangjing/opt/anaconda3/envs/pangolin/lib/python3.6/site-packages/lineages/data/anonymised.aln.safe.fasta.treefile key=/var/folders/yc/b8ybgrf57lv2b3hp_72sdfqh0000gn/T/tmp4bw9w7fz/query_key.csv --cores 1' returned non-zero exit status 1.
        File "/Users/yangjing/opt/anaconda3/envs/pangolin/lib/python3.6/site-packages/pangolin/scripts/assign_query_file.smk", line 75, in __rule_assign_lineages
        File "/Users/yangjing/opt/anaconda3/envs/pangolin/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        Exiting because a job execution failed. Look above for error message
        Exiting because a job execution failed. Look above for error message

**Comment by aineniamh** [comment]
Hi Jing,  
I'm not sure what the issue is from that output there, if you have some data that caused the error I can try to replicate the error and solve from that. Also, we're having a new pangolin release tomorrow, so it could be the case that the error gets solved with this new release anyway (it's quite a bit change).

**Comment by ISskandaR** [comment]
Dear there,
I'm writing you because I got some error while executing setup.py after having installed and entered conda pangolin environemnt. In particular the issue seems related to pandas library installation.
The set of Errors Log ends with 

File "/tmp/easy_install-_2Uj9u/pandas-1.1.0rc0/setup.py", line 349
    f"{extension}-source file '{sourcefile}' not found.\n"

Attached you can find the entire Error Log.
I appreciate any help.
Thanks a lot 
Valentino 

[PangolinErrorLog.txt](https://github.com/cov-lineages/pangolin/files/4967070/PangolinErrorLog.txt)

**Comment by aineniamh** [comment]
Hi Valentino, 

From the log you've attached it looks like there are two separate issues occuring. 
The first is there is a conflict with python versions in your system, pangolin runs in python 3 and the conda version you're running appears to have python 2.7 installed in addition to python 3. 
The second is that you don't seem to have permissions to write to the directory you've cloned pangolin into/ are trying to install pangolin into. 

```
bio@biows:~/bin/Pangolin_III/pangolin-master$ conda activate pangolin 
(pangolin) bio@biows:~/bin/Pangolin_III/pangolin-master$ python setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-26588.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/dist-packages/
```
I noticed you've then run with sudo, which is fine- but in general you may want to try installing it somewhere that you have write access to locally without that if possible. Other than that, from the looks of it, you've done everything right and it's just a conflicting set of python installs
```
bio@biows:~/bin/Pangolin_III/pangolin-master$ conda activate pangolin 
(pangolin) bio@biows:~/bin/Pangolin_III/pangolin-master$ python setup.py install
```
The above is all good, it's just that when it then tries to install it's running python2, which is why you get the following syntax errors:
```
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pangolin/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pangolin/scripts/find_all_snps.py to find_all_snps.pyc
  File "build/bdist.linux-x86_64/egg/pangolin/scripts/find_all_snps.py", line 40
    snp = f"{index}{col[0].upper()}{col[1].upper()}"
                                                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pangolin/scripts/pangolearn.py to pangolearn.pyc
byte-compiling build/bdist.linux-x86_64/egg/pangolin/scripts/lineage_finder.py to lineage_finder.pyc
byte-compiling build/bdist.linux-x86_64/egg/pangolin/scripts/get_masked_representatives.py to get_masked_representatives.pyc
  File "build/bdist.linux-x86_64/egg/pangolin/scripts/get_masked_representatives.py", line 39
    snp = f"{index}{col[0].upper()}{col[1].upper()}"
                                                   ^
SyntaxError: invalid syntax
```

My suggestion would be to check the version of conda you're running, check the python version in the pangolin environment (`python --version`), and it should be python 3.

Sometimes conda is a bit tricky with python versions and if it's proving complicated, it could be worth deleting conda, uninstalling and reinstalling it from scratch.

**Comment by ISskandaR** [comment]
Your answer has been very kind and precise, 
I really appreciate your help, as soon as I fix it I'll let you have a feedback.
Thanks so much for your work

**Comment by ISskandaR** [comment]
Hi Dear,
sorry for my answer's lateness.
I easily installed and successfully launched your software after the installation of anaconda3 environment.
I initially tried to perform the same task by  typing "python3 setup.py install" and it worked but a lot of package inconsistencies arose . Only by installing the Anaconda version 3 the problem has been solved.
I thanks you for your work
Valentino

**Comment by aineniamh** [comment]
Ah great! I'm glad it's all worked for you now! 

Thanks for the feedback Valentino!
